<a href="https://colab.research.google.com/github/royerlozano/CUADERNO-DE-ROYER/blob/main/Guia5MetNumericos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***ALGORITMO DE GAUSS JORDAN***
#METODOS NUMERICOS

In [6]:
import numpy as np
#tamaño de nuestra matriz
n = int(input("ingrese el valor de n: "))
Matriz = array = np.arange(n*(n+1)*1.0).reshape(n,n+1)
Rspta = array = np.arange(n).reshape(n,1)
#leemos los datos de nuestra matriz
for i in range(0,n):
  for j in range(0,n+1):
    Matriz[i,j] = float (input("ingrese la matriz["+str(i)+","+str(j)+"]: "))
print(Matriz)
#solucion del sistema de ecuaciones
for i in range(0,n):
  if (Matriz[i,i]== 0):
    print("Error matemático",i)
    break
  for j in range(0,n):
    if (i!=j):
      ratio = Matriz[j,i] / Matriz[i,i]
      for k in range(0,n+1):
        Matriz[j,k]=Matriz[j,k] - ratio*Matriz[i,k]
#soluciones
print('nuestra Rspta es: ')
for i in range(0,n):
  Rspta[i]= Matriz[i,n] / Matriz[i,i]
  print(Matriz[i,n] / Matriz[i,i])


ingrese el valor de n: 3
ingrese la matriz[0,0]: 2
ingrese la matriz[0,1]: 1
ingrese la matriz[0,2]: -1
ingrese la matriz[0,3]: 1
ingrese la matriz[1,0]: 5
ingrese la matriz[1,1]: 2
ingrese la matriz[1,2]: 2
ingrese la matriz[1,3]: -4
ingrese la matriz[2,0]: 3
ingrese la matriz[2,1]: 1
ingrese la matriz[2,2]: 1
ingrese la matriz[2,3]: 5
[[ 2.  1. -1.  1.]
 [ 5.  2.  2. -4.]
 [ 3.  1.  1.  5.]]
nuestra Rspta es: 
14.0
-32.0
-5.0
